---
- hosts: xchat7
  tasks:
  - name: Ensure sl is at the latest version
    ansible.builtin.package:
      name: sl
      state: latest
    become: true
  - name: example copying file with owner and permissions
    copy:
      src: foo.conf
      dest: /etc/foo.conf
  - name: Fetch os-relase
    fetch:
      src: /etc/os-release
      dest: /tmp/fetched
